#############################################
# SwAV-specific defaults for WILDS Datasets #
#############################################

# TODO: update these defaults. remove any we won't need for SwAV -Tony
DATASET_DEFAULTS = {
    'camelyon17': {
        'split_scheme': 'official',
        'model': 'densenet121',
        'model_kwargs': {},
        'train_transform': 'image_base',
        'eval_transform': 'image_base',
        'target_resolution': (96, 96),
        'loss_function': 'cross_entropy',
        'optimizer': 'SGD',
        'optimizer_kwargs': {'momentum': 0.9},
        'scheduler': None,
        'batch_size': 32,
        'lr': 0.001,
        'final_lr': 0.001 / 1000.,
        'weight_decay': 0.01,
        'epsilon': 0.03,
        'nmb_prototypes': 3000,
        'queue_length': 3840,
        'epoch_queue_starts': 500,
        'warmup_epochs': 0,
        'n_epochs': 5,
        'algo_log_metric': 'accuracy',
        'process_outputs_function': 'multiclass_logits_to_pred',
        'loader_kwargs': {
            'num_workers': 8,
            'pin_memory': True,
            'drop_last': True,
        },
    },
    'domainnet': {
        'split_scheme': 'official',
        'dataset_kwargs': {
            'source_domain': 'sketch',
            'target_domain': 'real',
            'use_sentry': True,
        },
        'model': 'resnet50',
        'model_kwargs': {},
        'train_transform': None,
        'eval_transform': None,
        'resize_scale': 256.0 / 224.0,
        'target_resolution': (224, 224),
        'loss_function': 'cross_entropy',
        'batch_size': 32,
        'unlabeled_batch_size': 32,
        'optimizer': 'SGD',
        'lr': 0.001,
        'final_lr': 0.001 / 1000.,
        'weight_decay': 1e-3,
        'epsilon': 0.03,
        'nmb_prototypes': 3000,
        'queue_length': 3840,
        'epoch_queue_starts': 500,
        'warmup_epochs': 0,
        'n_epochs': 400,
        'algo_log_metric': 'accuracy',
        'process_outputs_function': 'multiclass_logits_to_pred',
        'loader_kwargs': {
            'num_workers': 8,
            'pin_memory': True,
            'drop_last': True,
        },
    },
    'fmow': {
        'split_scheme': 'official',
        'dataset_kwargs': {
            'seed': 111,
            'use_ood_val': True
        },
        'model': 'densenet121',
        'model_kwargs': {},
        'target_resolution': (224, 224),
        'train_transform': 'image_base',
        'eval_transform': 'image_base',
        'loss_function': 'cross_entropy',
        'optimizer': 'Adam',
        'scheduler': 'StepLR',
        'scheduler_kwargs': {'gamma': 0.96},
        'batch_size': 32,
        'unlabeled_batch_size': 32,
        'lr': 0.0001,
        'final_lr': 0.0001 / 1000.,
        'weight_decay': 0.0,
        'warmup_epochs': 0,
        'epsilon': 0.03,
        'nmb_prototypes': 3000,
        'queue_length': 3840,
        'epoch_queue_starts': 500,
        'n_epochs': 50,
        'algo_log_metric': 'accuracy',
        'process_outputs_function': 'multiclass_logits_to_pred',
        'loader_kwargs': {
            'num_workers': 8,
            'pin_memory': True,
            'drop_last': True,
        },
    },
    'iwildcam': {
        'loss_function': 'cross_entropy',
        'val_metric': 'F1-macro_all',
        'train_transform': 'image_base',
        'eval_transform': 'image_base',
        'target_resolution': (448, 448),
        'model': 'resnet50',
        'model_kwargs': {},
        'lr': 3e-5,
        'final_lr': 3e-5 / 1000.,
        'weight_decay': 0.0,
        'batch_size': 16,
        'warmup_epochs': 0,
        'epsilon': 0.03,
        'nmb_prototypes': 3000,
        'queue_length': 3840,
        'epoch_queue_starts': 500,
        'n_epochs': 12,
        'optimizer': 'Adam',
        'split_scheme': 'official',
        'scheduler': None,
        'groupby_fields': ['location'],
        'no_group_logging': True,
        'process_outputs_function': 'multiclass_logits_to_pred',
        'loader_kwargs': {
            'num_workers': 8,
            'pin_memory': True,
            'drop_last': True,
        },
    },
    'poverty': {
        'split_scheme': 'official',
        'dataset_kwargs': {
            'no_nl': False,
            'fold': 'A',
            'use_ood_val': True
        },
        'model': 'resnet18_ms',
        'model_kwargs': {'num_channels': 8},
        'train_transform': 'poverty_train',
        'eval_transform': None,
        'target_resolution': (224, 224),
        'loss_function': 'mse',
        'optimizer': 'Adam',
        'scheduler': 'StepLR',
        'scheduler_kwargs': {'gamma': 0.96},
        'batch_size': 64,
        'lr': 0.001,
        'final_lr': 0.001 / 1000.,
        'weight_decay': 0.0,
        'epsilon': 0.03,
        'nmb_prototypes': 3000,
        'queue_length': 3840,
        'epoch_queue_starts': 500,
        'warmup_epochs': 0,
        'n_epochs': 200,
        'process_outputs_function': None,
        'loader_kwargs': {
            'num_workers': 8,
            'pin_memory': True,
            'drop_last': True,
        },
    }
}